### ISSUE TITLE
Image update (regular) release

### ISSUE THREAD

**Issue by dsimansk** [redhat-ipaas/karma-xvfb-docker#1]
Hi @iocanel @jimmidyson,

we should probably update `latest` image to freshen up packages like Chrome browser, yarn etc. Wdyt?

**Comment by jimmidyson** [comment]
Switched to automated build on Docker hub so update can be triggered any time just by clicking `Trigger` at https://hub.docker.com/r/syndesis/karma-xvfb/~/settings/automated-builds/.

I've just done so and an updated version is now available.

**Comment by dsimansk** [comment]
Thanks @jimmidyson 👍
